# Generated by Django 4.2.1 on 2023-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=100, verbose_name='docente')),
                ('solicitudes', models.CharField(max_length=100, verbose_name='Solicitudes')),
                ('disponibilidades', models.CharField(max_length=100, verbose_name='Disponibilidad')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actialización')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especializacion', models.CharField(max_length=200, verbose_name='Especialización')),
                ('materias', models.CharField(max_length=100, verbose_name='Materias')),
                ('celular', models.FloatField(verbose_name='Celular')),
                ('foto', models.CharField(max_length=100, verbose_name='Ruta img')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actialización')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('programa', models.CharField(max_length=200, verbose_name='Programa')),
                ('materias', models.CharField(max_length=100, verbose_name='Materias')),
                ('celular', models.FloatField(verbose_name='Celular')),
                ('foto', models.CharField(max_length=100, verbose_name='Ruta img')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actialización')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Materia')),
                ('programa', models.CharField(max_length=100, verbose_name='Prorama')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actialización')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asesoria')),
                ('estado', models.BooleanField(verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actialización')),
                ('docente', models.ManyToManyField(to='docentes.docente', verbose_name='Docente')),
                ('estudiante', models.ManyToManyField(to='docentes.estudiante', verbose_name='Estudiante')),
                ('materia', models.ManyToManyField(to='docentes.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Asesoria',
                'verbose_name_plural': 'Asesorias',
            },
        ),
    ]
