# Generated by Django 4.2.1 on 2023-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='docente',
            field=models.ManyToManyField(blank=True, null=True, to='docentes.docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='estudiante',
            field=models.ManyToManyField(blank=True, null=True, to='docentes.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='materia',
            field=models.ManyToManyField(blank=True, null=True, to='docentes.materia', verbose_name='Materia'),
        ),
    ]
