# Generated by Django 4.2.1 on 2023-06-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0006_alter_docente_foto_alter_estudiante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='comentarios',
            field=models.CharField(default='Aquí van tus com', max_length=500, verbose_name='Comentarios'),
        ),
    ]
