# Generated by Django 4.2.1 on 2023-06-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0007_asesoria_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actialización')),
            ],
        ),
        migrations.DeleteModel(
            name='EstadoSolicitud',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='estado',
        ),
        migrations.AddField(
            model_name='asesoria',
            name='estado',
            field=models.ManyToManyField(blank=True, null=True, to='docentes.estado', verbose_name='Estado de la Solicitud'),
        ),
    ]
