# Generated by Django 4.2.1 on 2023-06-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0008_estado_delete_estadosolicitud_remove_asesoria_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='asesoria',
            name='tipoSolicitud',
            field=models.CharField(choices=[('Investigación', 'Investigación'), ('Académica', 'Académica')], default='Académica', max_length=15),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='comentarios',
            field=models.CharField(max_length=500, verbose_name='Comentarios'),
        ),
    ]
