# Generated by Django 4.2.1 on 2023-06-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0009_alter_estado_options_asesoria_tiposolicitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoria',
            name='estado',
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='tipoSolicitud',
            field=models.CharField(choices=[('Investigación', 'Investigación'), ('Académica', 'Académica')], default='Académica', max_length=15, verbose_name='Tipo de Asesoria'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='estado',
            field=models.CharField(choices=[('Creada', 'Creada'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], default='Creada', max_length=15, verbose_name='Estado'),
        ),
    ]
