# Generated by Django 4.2.1 on 2023-06-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0010_remove_asesoria_estado_alter_asesoria_tiposolicitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=50, verbose_name='Días')),
                ('hora', models.TimeField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
