# Generated by Django 4.2.1 on 2023-06-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0011_horario_delete_agenda_delete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='biografia',
            field=models.CharField(default='0', max_length=1000, verbose_name='Biografía'),
        ),
    ]
