# Generated by Django 4.2.1 on 2023-06-14 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0012_docente_biografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='hora',
            new_name='horaH',
        ),
    ]
