# Generated by Django 4.2.1 on 2023-06-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0013_rename_hora_horario_horah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='horaH',
        ),
        migrations.AddField(
            model_name='horario',
            name='horario',
            field=models.CharField(default=' ', max_length=50, verbose_name='Horarios'),
        ),
    ]
