# Generated by Django 4.2.1 on 2023-06-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0014_remove_horario_dia_remove_horario_horah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='docentes.horario', verbose_name='Horarios'),
        ),
    ]
