# Generated by Django 4.2.1 on 2023-06-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0015_docente_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Programa')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programa',
            },
        ),
    ]
