# Generated by Django 4.2.1 on 2023-06-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0016_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='programa',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='programa',
            field=models.ManyToManyField(blank=True, null=True, to='docentes.programa', verbose_name='Programa'),
        ),
    ]
