# Generated by Django 4.2.1 on 2023-06-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0017_remove_estudiante_programa_estudiante_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=500, verbose_name='Tema')),
                ('problema', models.CharField(max_length=10000, verbose_name='Problema')),
                ('soluciónP', models.CharField(max_length=10000, verbose_name='Solución Planetada')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actialización')),
                ('materia', models.ManyToManyField(blank=True, null=True, to='docentes.materia', verbose_name='Materia')),
            ],
        ),
    ]
